name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build project
        run: mvn clean package

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          name: New release of ticketing-gui ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: 'target/ticketing-gui-1.0-SNAPSHOT-jar-with-dependencies.jar'

